BookApp/BookApp/urls.py
from django.contrib import admin
from django.urls import path
from Book.views import book_create, index, update_delete_book
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", index, name= 'index'),
    path('book/', book_create, name='book_create'),
    path('book/<int:id>',update_delete_book, name="others")
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

BookApp/Book/models.py
from django.db import models

# Create your models here.

class Book(models.Model):
    name = models.CharField(max_length=60)
    author = models.CharField(max_length=50)
    isbn = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name

BookApp/Book/forms.py
from django import forms
from .models import Book

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = "__all__"

BookApp/Book/views.py
from django.shortcuts import render
from django.http.response import JsonResponse, HttpResponse ,HttpResponseBadRequest
from .models import Book
from .forms import BookForm
from django.core import serializers
import json
from django.shortcuts import get_object_or_404
# Create your views here.

def index(request):
    is_ajax_request = request.headers.get("X-Requested-With") == 'XMLHTTPRequest'
    form = BookForm()
    if is_ajax_request:
        if request.method == "GET":
            data = list(Book.objects.all().values)
            return JsonResponse({'context': data})
    context = {
        "books":Book.objects.all(),
        "form":form
    }
    return render(request, "index.html", context=context)


def book_create(request):
    is_ajax = request.headers.get("X-Requested-With") == "XMLHttpRequest"
    if is_ajax:
        if request.method == "POST":
            data = json.load(request)
            print(data)
            book = data.get("payload")
            obj = Book.objects.create(name = book["name"],
                               author = book["author"] ,
                               isbn = book["isbn"])
            return JsonResponse({"status": "book added", "books":{"id":obj.id,
                                                                "name":obj.name,
                                                                "author":obj.author,
                                                                "isbn":obj.isbn} })
        return JsonResponse({"status":"invalid request"}, status=400)
    return HttpResponseBadRequest()



def update_delete_book(request, id):
    is_ajax = request.headers.get("X-Requested-With") == "XMLHttpRequest"
    if is_ajax:
        if request.method == "PUT":
            obj = Book.objects.get(id=id)

            data = json.load(request)
            updated_data = data.get("payload")

            obj.name = updated_data["name"]
            obj.isbn = updated_data["isbn"]
            obj.author = updated_data["author"]
            obj.save()
            return JsonResponse({"status":"Updated", "book":{"id":obj.id,
                                                                "name":obj.name,
                                                                "author":obj.author,
                                                                "isbn":obj.isbn}})
        if request.method == "DELETE":
            obj = Book.objects.get(id=id)
            obj.delete()
            return JsonResponse({"status":"deleted"})
        return JsonResponse({"status":"invalid request"}, status=400)
    return HttpResponseBadRequest()

BookApp/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
</head>
<body>
<div id="whole">
    {% for book in books%}

    <div class="container" id="container-{{ book.id }}">
        <div id="individual_book">

            <p id="book-{{book.id}}">{{book.name}}</p>
            <p id="book-author-{{book.id}}">{{book.author}}</p>
            <p id="book-isbn-{{book.id}}">{{book.isbn}}</p>

    <button id="update-{{book.id}}" value="Update"
            onclick="loadForm"> Update </button>

    <button id="delete-{{book.id}}" value="Delete"
            onclick="deleteBook(event, id=this.id)">Delete</button>
        </div>
        <div id="book-div-{{book.id}}">
        {% csrf_token %}


    </div>
        </div>


    <script>
        document.getElementById("update-{{book.id}}").addEventListener("click", loadUpdateForm)
        function loadUpdateForm(e) {
            e.preventDefault()

            let output = ""
            output +=`<div class="col-4 offset-4 mb-5 mt-5">
        <div class="content-section">
            <form method="POST" enctype="multipart/form-data">

                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Create Post</legend>
                  <tr><th><label for="id_name">Name:</label></th><td><input type="text" name="name" maxlength="60" required id="id_name" value="{{book.name}}"></td></tr>
<tr><th><label for="id_author">Author:</label></th><td><input type="text" name="author" maxlength="50" required id="id_author" value="{{book.author}}"></td></tr>
<tr><th><label for="id_isbn">Isbn:</label></th><td><input type="text" name="isbn" maxlength="50" required id="id_isbn" value="{{book.isbn}}"></td></tr>
                </fieldset>

            </form>
            <form id="updateform" class="form-group">
        <input class="btn btn-outline.info" type="submit" value="submit" onclick="updateBook(event, id={{book.pk}})">

                </form>
        </div>
</div>`
            //console.log(output)
                document.getElementById("book-div-{{book.id}}").innerHTML = output


        }



    </script>
    {% endfor %}

    <div id = "form-div">
        {% csrf_token %}


    </div>



</div>
    <button id="create" type="button"> Create New Book </button>




    <script src = '{% static "js/main.js"%}'>


    </script>
</body>

</html>